spring:
  application:
    name: subscription-service

  profiles:
    default: local

  config:
    import: optional:file:.env[.properties]

server:
  port: ${APP_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health

portone:
  api:
    base-url: ${PORTONE_API_BASE_URL:https://api.portone.io}
    secret: ${PORTONE_API_SECRET}

payment:
  billing-key:
    encryption-key: ${PAYMENT_BILLING_KEY_ENCRYPTION_KEY}