spring:
  application:
    name: subscription-service

  profiles:
    default: local

  config:
    import: optional:file:.env[.properties]

server:
  port: ${APP_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health